### ISSUE TITLE
pip 에서 chardet 2.0.1 이 더이상 지원되지 않고 gyp 는 못찾는군요.

### ISSUE THREAD

**Issue by jinto** [ukjin1192/political-survey#1]
현재 버전이 python2에서 동작하는 것이 맞는지요.
chardet 은 어쩐지 2.0.1이 동작하지 않네요.

mac osx 에서 pip는 다음 과정이 필요합니다. 문서에 추가하면 처음 설치하시는 분들께 도움될 듯 합니다.

```
virtualenv -p /usr/bin/python venv
source venv/bin/activate
# npm install -g node-gyp
git clone https://chromium.googlesource.com/external/gyp
cd gyp
sudo ./setup.py install
cd ..
pip install --upgrade pip
pip install -r conf/pip/requirements.txt
```

**Comment by ukjin1192** [comment]
이 repository 를 Private repository 처럼 사용하다보니 환경 세팅에 대한 부분을 제가 명시 안 했군요.

서비스는, 
- Python 2.7.X 를 사용합니다.
- Ubuntu 를 기준으로 하고 있습니다.
- Virtualenv 를 사용하고 있지 않습니다. (대신 Docker 를 사용해서 base 가 되는 image 를 만들어놓고 필요할 때마다 container 를 만들어서 사용합니다)

해당 내용을 README 에 반영한 후에 close 하도록 하겠습니다.
감사합니다 :)

**Comment by jinto** [comment]
그랬군요. public repo라서 따라하다가 이슈를 올려보았습니다.
문서에 docker 관련 항목도 반영되면 좋겠습니다.
감사합니다. ^^

**Comment by ukjin1192** [comment]
해당 부분이 명시가 안 되어 있어서 제권님께서 혼란이 됐을 것 같아요.
알려주셔서 감사합니다. docker 부분도 반영할 수 있도록 하겠습니다!
MVP 만들고 나서 추가하도록 하겠습니다. :+1:

**Comment by ukjin1192** [comment]
해당 부분을 아래에 반영했습니다. 감사합니다!

- conf/pip/requirements.txt
- conf/pip/pre-requirements.txt
