### ISSUE TITLE
데이터문제이긴 합니다만.. 첫번째 질문의 문장

### ISSUE THREAD

**Issue by jinto** [ukjin1192/political-survey#2]
첫번째 질문은 "북한 문제에 대해 우리 정부는?" 이 맞는 것 같습니다.

**Comment by ukjin1192** [comment]
감사합니다!
수정 완료했습니다 :)
현재 질문 set 를 수정하고, 정당들로부터 답변을 받아서 3/25에 정식 release 할 예정입니다!
